;;;; Lisp File : clisp-0-0-0-2-0.el
;;;; Purpose   : Testing the template.
;;;; Created   : Sunday, May 23 2021.
;;;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;;;; -----------------------------------------------------------------------------------------------
;;;; Commentary:
;;;;
;;;; [
;;;; This text inside the square brackets is normally NOT generated by the template!
;;;; It is here only to show the value of the user-options used to generate the content.
;;;; This file was generated by the test function: pel--clisp-all-sk-file-header
;;;; This file was generated with the following user-options values:
;;;; - pel-clisp-skel-use-separators        : nil
;;;; - pel-clisp-skel-insert-file-timestamp : nil
;;;; - pel-clisp-skel-with-license          : nil
;;;; - pel-clisp-skel-package-name          : "foo"
;;;; - pel-clisp-emacs-filevar-line         : nil
;;;;  ]

;;;; -----------------------------------------------------------------------------------------------
;;;; Dependencies:
;;;;
;;;;

;;;; -----------------------------------------------------------------------------------------------
;;;; Code:
;;;;


;;;; -----------------------------------------------------------------------------------------------
