;;;; Lisp File : clisp-0-0-1-0-0.el
;;;; Purpose   : Testing the template.
;;;; Created   : Sunday, May 23 2021.
;;;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;;;;
;;;; Copyright (C) 2021  Pierre Rouleau
;;;;
;;;; Permission is hereby granted, free of charge, to any person obtaining a copy
;;;; of this software and associated documentation files (the "Software"), to deal
;;;; in the Software without restriction, including without limitation the rights
;;;; to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
;;;; copies of the Software, and to permit persons to whom the Software is
;;;; furnished to do so, subject to the following conditions:
;;;; The above copyright notice and this permission notice shall be included in
;;;; all copies or substantial portions of the Software.
;;;;
;;;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
;;;; IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
;;;; FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
;;;; AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
;;;; LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
;;;; OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
;;;; THE SOFTWARE.
;;;;
;;;; -----------------------------------------------------------------------------------------------
;;;; Commentary:
;;;;
;;;; [
;;;; This text inside the square brackets is normally NOT generated by the template!
;;;; It is here only to show the value of the user-options used to generate the content.
;;;; This file was generated by the test function: pel--clisp-all-sk-file-header
;;;; This file was generated with the following user-options values:
;;;; - pel-clisp-skel-use-separators        : nil
;;;; - pel-clisp-skel-insert-file-timestamp : nil
;;;; - pel-clisp-skel-with-license          : t
;;;; - pel-clisp-skel-package-name          : nil
;;;; - pel-clisp-emacs-filevar-line         : nil
;;;;  ]

;;;; -----------------------------------------------------------------------------------------------
;;;; Dependencies:
;;;;
;;;;

;;;; -----------------------------------------------------------------------------------------------
;;;; Code:
;;;;


;;;; -----------------------------------------------------------------------------------------------
