;;; pel-skels-elisp-test.el --- Test the Emacs Lisp Skeletons.  -*- lexical-binding: t; -*-

;; Created   : Saturday, May 22 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;; Time-stamp: <2021-05-25 14:43:20, updated by Pierre Rouleau>

;; This file is part of the PEL package.
;; This file is not part of GNU Emacs.

;; Copyright (C) 2021  Pierre Rouleau
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; --------------------------------------------------------------------------
;;; Commentary:
;;
;;

;;; --------------------------------------------------------------------------
;;; Dependencies:
;;
;;
(require 'pel--options)
(require 'pel-ert)
(require 'cl-lib)
;;; --------------------------------------------------------------------------
;;; Code:
;;

(defun pel--elisp-all-sk-file-header (directory file-base-name &optional license-name)
  "Generate all supported layouts of the Emacs Lisp templates in DIRECTORY.
Each generated file name use the FILE-NAME-BASE as the base name,
then an extra number patter is added to it to create the file name."
  (let ((base-name (expand-file-name file-base-name directory))
        file-name
        pel-elisp-skel-use-separators        (f1 -1)
        pel-elisp-skel-insert-file-timestamp (f2 -1)
        pel-elisp-skel-with-license          (f3 -1)
        pel-elisp-skel-package-name          (f4 -1)
        (license-name                        (or license-name "gpl-3.0")))
    (cl-letf (((symbol-function 'read-from-minibuffer)
               (lambda (_prompt &optional
                                _initial-content
                                _keymap
                                _read
                                _hist
                                _default-value
                                _inherit-input-method)
                 "testing the template")))
      (cl-letf (((symbol-function 'lice:read-license)
                 (lambda ()
                   license-name)))
        (dolist (pel-elisp-skel-use-separators
                 (get 'pel-elisp-skel-use-separators :choices))
          (progn
            (cl-incf f1)
            (setq f2 -1)
            (dolist (pel-elisp-skel-insert-file-timestamp
                     (get 'pel-elisp-skel-insert-file-timestamp :choices))
              (progn
                (cl-incf f2)
                (setq f3 -1)
                (dolist (pel-elisp-skel-with-license
                         (get 'pel-elisp-skel-with-license :choices))
                  (progn
                    (cl-incf f3)
                    (setq f4 -1)
                    (dolist (pel-elisp-skel-package-name
                             (get 'pel-elisp-skel-package-name :choices))
                      (progn
                        (cl-incf f4)
                        (setq file-name (format "%s-%d-%d-%d-%d.el" base-name f1 f2 f3 f4))
                        (message "Testing with %s: %S, %S, %S, %S"
                                 file-name
                                 pel-elisp-skel-use-separators
                                 pel-elisp-skel-insert-file-timestamp
                                 pel-elisp-skel-with-license
                                 pel-elisp-skel-package-name)
                        (find-file file-name)
                        (erase-buffer)
                        (emacs-lisp-mode)
                        (pel-elisp-file-header)
                        (insert (format "[
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : %S
;; - pel-elisp-skel-insert-file-timestamp : %S
;; - pel-elisp-skel-with-license          : %S
;; - pel-elisp-skel-package-name          : %S
;;  ]"
                                        pel-elisp-skel-use-separators
                                        pel-elisp-skel-insert-file-timestamp
                                        pel-elisp-skel-with-license
                                        pel-elisp-skel-package-name))
                        (write-file file-name)
                        (kill-buffer)))))))))))))

(defun pel--elisp-all-sk-files ()
  "Generate Emacs Lisp skeleton template files with all possible combinations.
Store them inside the pel/test-result/templates/elisp directory."
  (interactive)
  (let ((dir-name (expand-file-name
                   "test-result/templates/elisp" (file-name-directory (locate-library "pel--options")))))
    (pel--elisp-all-sk-file-header dir-name "elisp")))

;;; --------------------------------------------------------------------------
(provide 'pel-skels-elisp-test)

;;; pel-skels-elisp-test.el ends here
