%%% @author Pierre Rouleau <prouleau001@gmail.com>
%%% @copyright (C) 2021, Pierre Rouleau
%%% @doc
%%%[
%   This text inside the square brackets is normally NOT generated by the template!
%   It is here only to show the value of the user-options used to generate the content.
%   This file was generated by the test function: pel--erlang-all-sk-file-header
%   This file was generated with the following user-options values:
%   - pel-erlang-skel-use-separators        : t
%   - pel-erlang-skel-use-secondary-separators : t
%   - pel-erlang-skel-insert-file-timestamp          : t
%   - pel-erlang-skel-with-license          : "MIT"
%   - pel-erlang-skel-with-edoc         : in-function-only
%    ]
%%% @end
%%% Created: 2021-05-23 by Pierre Rouleau <prouleau001@gmail.com>

-module(normal_header_1_1_1_2_2).
