%%% ------------------------------------------------------------------------------------------------
%%% File      : small_server_1_1_1_2_2.erl
%%% Purpose   : Testing the template.
%%% Created   : Sunday, May 23 2021.
%%% Author    : Pierre Rouleau <prouleau001@gmail.com>
%%% Time-stamp: <2021-05-23 02:36:42, updated by Pierre Rouleau>
%%% Copyright © 2021, Pierre Rouleau
%%% License   : MIT
%%% ------------------------------------------------------------------------------------------------
%%% Module Description: Testing the template.
%%%
%%% [
%   This text inside the square brackets is normally NOT generated by the template!
%   It is here only to show the value of the user-options used to generate the content.
%   This file was generated by the test function: pel--erlang-all-sk-file-header
%   This file was generated with the following user-options values:
%   - pel-erlang-skel-use-separators        : t
%   - pel-erlang-skel-use-secondary-separators : t
%   - pel-erlang-skel-insert-file-timestamp          : t
%   - pel-erlang-skel-with-license          : "MIT"
%   - pel-erlang-skel-with-edoc         : in-function-only
%    ]
%%% ================================================================================================
-module(small_server_1_1_1_2_2).

-export([start/0, init/1]).


start() ->
    spawn(small_server_1_1_1_2_2, init, [self()]).

init(From) ->
    loop(From).

loop(From) ->
    receive
        _ ->
            loop(From)
    end.
