/* C HEADER: example_0_1_2_0_0_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:44:53, updated by Pierre Rouleau>
 * Copyright © 2021, Pierre Rouleau
 * License   : MIT
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_0_1_2_0_0_0__H_07CA8E6D_8BA8_4D24_9968_8FDE21C3525A
#define EXAMPLE_0_1_2_0_0_0__H_07CA8E6D_8BA8_4D24_9968_8FDE21C3525A /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
