/* C HEADER: example-1-0-0-1-1-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-0-0-1-1-1__H_23AB3A96_98A6_4484_942D_B97C2952ED74
#define EXAMPLE-1-0-0-1-1-1__H_23AB3A96_98A6_4484_942D_B97C2952ED74 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
