/* C HEADER: example-1-0-0-0-1-0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-0-0-0-1-0__H_CD77FE1B_705E_4CFC_8BEE_0075F8B5C65B
#define EXAMPLE-1-0-0-0-1-0__H_CD77FE1B_705E_4CFC_8BEE_0075F8B5C65B /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
