/* C MODULE: example_1_1_1_1_1_1.c
**
** Purpose   : Testing the template.
** Created   : Tuesday, May 25 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-25 12:34:32, updated by Pierre Rouleau>
** Copyright © 2021, Pierre Rouleau
*/
/* -------------------------------------------------------------------------- */
/* Module Description
** ------------------
*/

/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : only-copyright
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/

/* -------------------------------------------------------------------------- */
/* Header Inclusion
** ----------------
*/



/* -------------------------------------------------------------------------- */
/* Local Types
** -----------
*/



/* -------------------------------------------------------------------------- */
/* Local Variables
** ---------------
*/



/* -------------------------------------------------------------------------- */
/* Code
** ----
*/



/* -------------------------------------------------------------------------- */
