/* C HEADER: example_0_0_2_0_0_1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Copyright © 2021, Pierre Rouleau
** License   : MIT
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_0_0_2_0_0_1__H_7CF53C03_D4B4_46CD_B4C7_89344A12B6DB
#define EXAMPLE_0_0_2_0_0_1__H_7CF53C03_D4B4_46CD_B4C7_89344A12B6DB /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
