/* C HEADER: example-1-1-0-0-0-0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:12:02, updated by Pierre Rouleau>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-1-0-0-0-0__H_7505579C_434B_43B0_8807_2DF8F27F06F4
#define EXAMPLE-1-1-0-0-0-0__H_7505579C_434B_43B0_8807_2DF8F27F06F4 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
