/* C MODULE: example_1_0_2_1_0_1.c
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Copyright © 2021, Pierre Rouleau
** License   : MIT
*/
/* -------------------------------------------------------------------------- */
/* -------------------------------------------------------------------------- */
/* Module Description
** ------------------
*/

/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/

/* -------------------------------------------------------------------------- */
/* Header Inclusion
** ----------------
*/



/* -------------------------------------------------------------------------- */
/* Local Types
** -----------
*/



/* -------------------------------------------------------------------------- */
/* Local Variables
** ---------------
*/



/* -------------------------------------------------------------------------- */
/* Code
** ----
*/



/* -------------------------------------------------------------------------- */
