/* C HEADER: example_1_1_0_1_1_1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-23 01:44:57, updated by Pierre Rouleau>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_1_0_1_1_1__H_7F43BFA9_3D60_4595_B4B0_6F416EC977D7
#define EXAMPLE_1_1_0_1_1_1__H_7F43BFA9_3D60_4595_B4B0_6F416EC977D7 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
