/* C HEADER: example_0_0_0_1_0_1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_0_0_0_1_0_1__H_6D2783B3_82F1_40C9_BFC7_AB74930864AE
#define EXAMPLE_0_0_0_1_0_1__H_6D2783B3_82F1_40C9_BFC7_AB74930864AE /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
