/* C HEADER: example_1_0_0_1_0_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_0_0_1_0_0__H_F9435350_14BB_4B65_93A3_F2F671EC420C
#define EXAMPLE_1_0_0_1_0_0__H_F9435350_14BB_4B65_93A3_F2F671EC420C /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
