/* C HEADER: example-0-0-0-0-0-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-0-0-0-0-0-1__H_FC000B73_F29B_4243_B287_EFD9CFDE8BF5
#define EXAMPLE-0-0-0-0-0-1__H_FC000B73_F29B_4243_B287_EFD9CFDE8BF5 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
