/* C HEADER: example_1_1_0_0_0_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:44:56, updated by Pierre Rouleau>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_1_0_0_0_0__H_1FF03818_26ED_4266_9F0D_496D3771397B
#define EXAMPLE_1_1_0_0_0_0__H_1FF03818_26ED_4266_9F0D_496D3771397B /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
