/* C HEADER: example_1_1_3_1_1_1.h
**
** Purpose   : Testing the template.
** Created   : Tuesday, May 25 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-25 12:34:45, updated by Pierre Rouleau>
** Copyright © 2021, Pierre Rouleau
** License   : MIT
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_1_3_1_1_1__H_48BCD2EC_0F8D_4178_9F72_8DC2759EF1E2
#define EXAMPLE_1_1_3_1_1_1__H_48BCD2EC_0F8D_4178_9F72_8DC2759EF1E2 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
