/* C HEADER: example-1-0-2-0-0-0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Copyright © 2021, Pierre Rouleau
 * License   : MIT
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-0-2-0-0-0__H_88A93597_CB27_4502_91F1_654EE549FAC4
#define EXAMPLE-1-0-2-0-0-0__H_88A93597_CB27_4502_91F1_654EE549FAC4 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
