/* C HEADER: example_1_0_0_0_0_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Tuesday, May 25 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_0_0_0_0_0__H_C495D112_ACF7_452B_B1E2_EB7C75954F68
#define EXAMPLE_1_0_0_0_0_0__H_C495D112_ACF7_452B_B1E2_EB7C75954F68 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
