/* C HEADER: example-1-1-0-0-1-0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:12:02, updated by Pierre Rouleau>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-1-0-0-1-0__H_316479BC_7508_47E6_B2F9_E6D4AE5B59B9
#define EXAMPLE-1-1-0-0-1-0__H_316479BC_7508_47E6_B2F9_E6D4AE5B59B9 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
