/* C HEADER: example_1_0_2_1_1_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Copyright © 2021, Pierre Rouleau
 * License   : MIT
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_0_2_1_1_0__H_2E68622F_8DD9_4F10_A2DD_557C3E917A33
#define EXAMPLE_1_0_2_1_1_0__H_2E68622F_8DD9_4F10_A2DD_557C3E917A33 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
