/* C HEADER: example-0-1-0-0-0-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-23 01:11:58, updated by Pierre Rouleau>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-0-1-0-0-0-1__H_095DA64C_7728_4171_ABF2_7BCCCBD9FE2D
#define EXAMPLE-0-1-0-0-0-1__H_095DA64C_7728_4171_ABF2_7BCCCBD9FE2D /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
