/* C HEADER: example-1-1-0-1-1-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-23 01:12:02, updated by Pierre Rouleau>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-1-0-1-1-1__H_93BB51C5_E774_4318_9E38_86D85C1A35DF
#define EXAMPLE-1-1-0-1-1-1__H_93BB51C5_E774_4318_9E38_86D85C1A35DF /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
