/* C HEADER: example-0-1-2-0-1-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-23 01:12:00, updated by Pierre Rouleau>
** Copyright © 2021, Pierre Rouleau
** License   : MIT
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-0-1-2-0-1-1__H_905B32CB_F5A6_4F7C_B220_930BA6BEA275
#define EXAMPLE-0-1-2-0-1-1__H_905B32CB_F5A6_4F7C_B220_930BA6BEA275 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
