/* C HEADER: example_1_1_0_0_1_0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:44:56, updated by Pierre Rouleau>
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_1_1_0_0_1_0__H_A88945F0_2CFA_4ED4_842A_17627E584438
#define EXAMPLE_1_1_0_0_1_0__H_A88945F0_2CFA_4ED4_842A_17627E584438 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
