/* C HEADER: example-1-1-0-0-1-1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Time-stamp: <2021-05-23 01:12:02, updated by Pierre Rouleau>
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-1-0-0-1-1__H_1801C0D8_13F2_4D14_B453_31A785FD3215
#define EXAMPLE-1-1-0-0-1-1__H_1801C0D8_13F2_4D14_B453_31A785FD3215 /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
