/* C MODULE: example_0_1_0_0_1_0.c
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:44:43, updated by Pierre Rouleau>
 */
/* -------------------------------------------------------------------------- */

/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : nil
**   - pel-c-skel-module-section-titles : nil
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
