/* C HEADER: example-1-1-2-1-0-0.h
 *
 * Purpose   : Testing the template.
 * Created   : Sunday, May 23 2021.
 * Author    : Pierre Rouleau <prouleau001@gmail.com>
 * Time-stamp: <2021-05-23 01:12:03, updated by Pierre Rouleau>
 * Copyright © 2021, Pierre Rouleau
 * License   : MIT
 */
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE-1-1-2-1-0-0__H_E3B198DE_6DE0_4D14_AF32_5F361FC5911C
#define EXAMPLE-1-1-2-1-0-0__H_E3B198DE_6DE0_4D14_AF32_5F361FC5911C /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : t
**   - pel-c-skel-insert-file-timestamp : t
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : nil
**   - pel-c-skel-comment-with-2stars   : nil
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
