/* C HEADER: example_0_0_2_1_1_1.h
**
** Purpose   : Testing the template.
** Created   : Sunday, May 23 2021.
** Author    : Pierre Rouleau <prouleau001@gmail.com>
** Copyright © 2021, Pierre Rouleau
** License   : MIT
*/
/* -------------------------------------------------------------------------- */
#ifndef EXAMPLE_0_0_2_1_1_1__H_6287DF25_8FAE_4009_8699_FD2B3A12724F
#define EXAMPLE_0_0_2_1_1_1__H_6287DF25_8FAE_4009_8699_FD2B3A12724F /* include guard */
/* -------------------------------------------------------------------------- */
/*[
**   This text inside this comment in square brackets is normally NOT generated by the template!
**   It is here only to show the value of the user-options used to generate the content.
**   This file was generated by the test function: pel--c-all-sk-file-header
**   This file was generated with the following user-options values:
**   - pel-c-skel-use-separators        : nil
**   - pel-c-skel-insert-file-timestamp : nil
**   - pel-c-skel-with-license          : "MIT"
**   - pel-c-skel-module-section-titles : ("Module Description" "Header Inclusion" "Local Types" "Local Variables" "Code")
**   - pel-c-skel-doc-markup            : doxygen
**   - pel-c-skel-comment-with-2stars   : t
**    ]*/
/* -------------------------------------------------------------------------- */
#endif
