;;;; Lisp File : test-commonlisp.l
;;;; Purpose   : Test PEL Support for Common Lisp.
;;;; Created    Friday, May  1 2026.

;;;; -----------------------------------------------------------------------------------------------
;;;; Commentary:
;;;;
;;;; TOFIX: This file extension clashes with Flex/Bison file and is opened in flex-mode.
;;;;        A file type detector and dispatcher is needed.


;;;; -----------------------------------------------------------------------------------------------
;;;; Dependencies:
;;;;
;;;;

;;;; -----------------------------------------------------------------------------------------------
;;;; Code:
;;;;



;;;; -----------------------------------------------------------------------------------------------
