;;;; Lisp File : test-commonlisp.l
;;;; Purpose   : Test PEL Support for Common Lisp.
;;;; Created    Friday, May  1 2026.
;;;; Author     Pierre Rouleau <prouleau001@gmail.com>
;;;; Time-stamp: <2026-05-01 07:58:37 EDT, updated by Pierre Rouleau>

;;;; Copyright (C) 2026  Pierre Rouleau
;;;;
;;;; This program is free software: you can redistribute it and/or modify
;;;; it under the terms of the GNU General Public License as published by
;;;; the Free Software Foundation, either version 3 of the License, or
;;;; (at your option) any later version.
;;;;
;;;; This program is distributed in the hope that it will be useful,
;;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;; GNU General Public License for more details.
;;;;
;;;; You should have received a copy of the GNU General Public License
;;;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;;; -----------------------------------------------------------------------------------------------
;;;; Commentary:
;;;;
;;;; TOFIX: This file extension clashes with Flex/Bison file and is opened in flex-mode.
;;;;        A file type detector and dispatcher is needed.


;;;; -----------------------------------------------------------------------------------------------
;;;; Dependencies:
;;;;
;;;;

;;;; -----------------------------------------------------------------------------------------------
;;;; Code:
;;;;



;;;; -----------------------------------------------------------------------------------------------
