;;; elisp-1-0-2-2.el --- Testing the template.  -*- lexical-binding: t; -*-

;; Created   : Saturday, May 22 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>

;; This file is part of the foo package.
;; This file is not part of GNU Emacs.

;; Copyright © 2021, Pierre Rouleau
;; License   : MIT

;;; --------------------------------------------------------------------------
;;; Commentary:
;;
;; [
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : t
;; - pel-elisp-skel-insert-file-timestamp : nil
;; - pel-elisp-skel-with-license          : "MIT"
;; - pel-elisp-skel-package-name          : "foo"
;;  ]

;;; --------------------------------------------------------------------------
;;; Dependencies:
;;
;;

;;; --------------------------------------------------------------------------
;;; Code:
;;


;;; --------------------------------------------------------------------------
(provide 'elisp-1-0-2-2)

;;; elisp-1-0-2-2.el ends here
