;;; elisp-0-1-0-2.el --- Testing the template.  -*- lexical-binding: t; -*-

;; Created   : Tuesday, May 25 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;; Time-stamp: <2021-05-25 12:41:21, updated by Pierre Rouleau>
;; This file is part of the foo package.

;;; Commentary:
;;
;; [
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : nil
;; - pel-elisp-skel-insert-file-timestamp : t
;; - pel-elisp-skel-with-license          : nil
;; - pel-elisp-skel-package-name          : "foo"
;;  ]

;;; Dependencies:
;;
;;

;;; Code:
;;

(provide 'elisp-0-1-0-2)

;;; elisp-0-1-0-2.el ends here
