;;; elisp-0-1-1-2.el --- Testing the template.  -*- lexical-binding: t; -*-

;; Created   : Tuesday, May 25 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;; Time-stamp: <2021-05-25 12:41:21, updated by Pierre Rouleau>

;; This file is part of the foo package.
;; This file is not part of GNU Emacs.

;; Copyright (C) 2021  Pierre Rouleau
;;
;; This program is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.
;;
;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.
;;
;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:
;;
;; [
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : nil
;; - pel-elisp-skel-insert-file-timestamp : t
;; - pel-elisp-skel-with-license          : t
;; - pel-elisp-skel-package-name          : "foo"
;;  ]

;;; Dependencies:
;;
;;

;;; Code:
;;

(provide 'elisp-0-1-1-2)

;;; elisp-0-1-1-2.el ends here
