;;; elisp-1-0-3-0.el --- Testing the template.  -*- lexical-binding: t; -*-

;; Created   : Tuesday, May 25 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;; Copyright © 2021, Pierre Rouleau
;; License   : MIT

;;; --------------------------------------------------------------------------
;;; Commentary:
;;
;; [
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : t
;; - pel-elisp-skel-insert-file-timestamp : nil
;; - pel-elisp-skel-with-license          : "MIT"
;; - pel-elisp-skel-package-name          : nil
;;  ]

;;; --------------------------------------------------------------------------
;;; Dependencies:
;;
;;

;;; --------------------------------------------------------------------------
;;; Code:
;;

;;; --------------------------------------------------------------------------
(provide 'elisp-1-0-3-0)

;;; elisp-1-0-3-0.el ends here
