;;; elisp-0-1-3-1.el --- Testing the template.  -*- lexical-binding: t; -*-

;; Created   : Tuesday, May 25 2021.
;; Author    : Pierre Rouleau <prouleau001@gmail.com>
;; Time-stamp: <2021-05-25 12:41:21, updated by Pierre Rouleau>
;; Copyright © 2021, Pierre Rouleau
;; License   : MIT
;; This file is part of the ELISP package.

;;; Commentary:
;;
;; [
;; This text inside the square brackets is normally NOT generated by the template!
;; It is here only to show the value of the user-options used to generate the content.
;; This file was generated by the test function: pel--elisp-all-sk-file-header
;; This file was generated with the following user-options values:
;; - pel-elisp-skel-use-separators        : nil
;; - pel-elisp-skel-insert-file-timestamp : t
;; - pel-elisp-skel-with-license          : "MIT"
;; - pel-elisp-skel-package-name          : extract-from-file-name
;;  ]

;;; Dependencies:
;;
;;

;;; Code:
;;

(provide 'elisp-0-1-3-1)

;;; elisp-0-1-3-1.el ends here
