// D FILE: example_0_1_1_1.d
//
// Purpose   : Testing the template.
// Created   : Tuesday, May 25 2021.
// Author    : Pierre Rouleau <prouleau001@gmail.com>
// Time-stamp: <2021-05-25 14:44:36, updated by Pierre Rouleau>
// Copyright © 2021, Pierre Rouleau
// -----------------------------------------------------------------------------
// Module Description
// ------------------
//
// // [
//    This text inside this comment in square brackets is normally NOT generated by the template!
//    It is here only to show the value of the user-options used to generate the content.
//    This file was generated by the test function: pel--c-all-sk-file-header
//    This file was generated with the following user-options values:
//    - pel-generic-skel-use-separators        : nil
//    - pel-generic-skel-insert-file-timestamp : t
//    - pel-generic-skel-with-license          : only-copyright
//    - pel-generic-skel-module-section-titles : ("Module Description" "Dependencies" "Code")
//     ]


// Dependencies
// ------------
//
//


// Code
// ----
//
//
