// D FILE: example_0_0_0_1.d
//
// Purpose   : Testing the template.
// Created   : Tuesday, May 25 2021.
// Author    : Pierre Rouleau <prouleau001@gmail.com>
// -----------------------------------------------------------------------------
// Module Description
// ------------------
//
// // [
//    This text inside this comment in square brackets is normally NOT generated by the template!
//    It is here only to show the value of the user-options used to generate the content.
//    This file was generated by the test function: pel--c-all-sk-file-header
//    This file was generated with the following user-options values:
//    - pel-generic-skel-use-separators        : nil
//    - pel-generic-skel-insert-file-timestamp : nil
//    - pel-generic-skel-with-license          : nil
//    - pel-generic-skel-module-section-titles : ("Module Description" "Dependencies" "Code")
//     ]


// Dependencies
// ------------
//
//


// Code
// ----
//
//
