# YAML FILE: deplo-pdfs.yml
#
# Purpose   : Copy all PEL PDF files to a Pages site.
# Created   : Wednesday, May 20 2026.
# Author    : Pierre Rouleau <prouleau001@gmail.com>
# Time-stamp: <2026-05-20 15:24:56 EDT, updated by Pierre Rouleau>
# ----------------------------------------------------------------------------
# Module Description
# ------------------
#
#
# Copy the PEL PDF files into Github Pages to allow browser to render them
# easily.
#
# Github sends raw hosted PDF files with a HTTP header intended to force security
# isolation  (:Content-Disposition: attachment; filename=-index.pdf) and that
# prevents PDF rendering on most browsers except Firefox.  But it does not do
# that for PDF files stored in its Pages site.  Therefore this job will just
# copy them.

# ----------------------------------------------------------------------------
# Dependencies
# ------------
#
# Github actions, Github Pages

# ----------------------------------------------------------------------------
# Code
# ----
#
#

name: Deploy PEL PDFs to Pages

on:
  push:
    branches:
      - master  # Runs whenever updated by master branch
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload PDF Directory Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Take all files under doc/pdf directory tree.
          path: 'doc/pdf'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

# ----------------------------------------------------------------------------
